[general]
import = ["themes/tokyonight_moon.toml"]
live_config_reload = true

[window]
padding = { x = 0 , y = 0}
dynamic_padding = true

[font]
size = 12.00
normal = {family = "JetBrains Mono", style = "Regular" }
italic = {family = "JetBrains Mono", style = "Italic" }
bold = {family = "JetBrains Mono", style = "Bold" }
bold_italic = {family = "JetBrains Mono", style = "Bold Italic" }
