[general]
import = ["~/.config/alacritty/themes/rose_pine.toml"]
live_config_reload = true

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
padding = { x = 10 , y = 10}
dynamic_padding = true

[font]
size = 16.00
normal = {family = "TX-02", style = "Regular" }
bold = {family = "TX-02", style = "Bold" }
italic = {family = "TX-02", style = "Italic" }
bold_italic = {family = "TX-02", style = "Bold Italic" }

[terminal]
osc52 = "CopyPaste"
