[colors]
ansi = [
    "#1F1F28",
    "#c84053",
    "#6f894e",
    "#77713f",
    "#4d699b",
    "#b35b79",
    "#597b75",
    "#545464",
]
background = "#f2ecbc"
brights = [
    "#8a8980",
    "#d7474b",
    "#6e915f",
    "#836f4a",
    "#6693bf",
    "#624c83",
    "#5e857a",
    "#43436c",
]
compose_cursor = "#43436c"
cursor_bg = "#43436c"
cursor_border = "#43436c"
cursor_fg = "#43436c"
foreground = "#545464"
scrollbar_thumb = "#b5cbd2"
selection_bg = "#9fb5c9"
selection_fg = "#43436c"
split = "#b5cbd2"

# [colors.indexed]
# color_16 = "#e98a00" # extended color 1
# color_17 = "#e82424" # extended color 2
#
[colors.tab_bar]
background = "#e4d794"

[colors.tab_bar.active_tab]
bg_color = "#b35b79"
fg_color = "#f2ecbc"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#a6a69c"
fg_color = "#f2ecbc"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#9fb5c9"
fg_color = "#43436c"
intensity = "Normal"
italic = true
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#b35b79"
fg_color = "#f2ecbc"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#9fb5c9"
fg_color = "#43436c"
intensity = "Normal"
italic = true
strikethrough = false
underline = "None"

[metadata]
name = 'Kanagawa Lotus'
