[manager]
sort_by = "natural"
show_hidden = true

# [[plugin.prepend_fetchers]]
# id   = "mime"
# if   = "!(mime|dummy)"
# name = "*"
# run  = "mime-ext"
# prio = "high"
#
# [preview]
# image_delay = 0
